drop table country_code;
create table country_code (
    alpha_two_code varchar2(2) primary key,
    country_name varchar2(56)
);

insert into country_code values ('AD', 'Andorra');
insert into country_code values ('AE', 'United Arab Emirates');
insert into country_code values ('AF', 'Afghanistan');
insert into country_code values ('AG', 'Antigua and Barbuda');
insert into country_code values ('AI', 'Anguilla');
insert into country_code values ('AL', 'Albania');
insert into country_code values ('AM', 'Armenia');
insert into country_code values ('AO', 'Angola');
insert into country_code values ('AQ', 'Antarctica');
insert into country_code values ('AR', 'Argentina');
insert into country_code values ('AR', 'American Samoa');
insert into country_code values ('AT', 'Austria');
insert into country_code values ('AU', 'Australia');
insert into country_code values ('AW', 'Aruba');
insert into country_code values ('AX', 'Åland Islands');
insert into country_code values ('AZ', 'Azerbaijan');
insert into country_code values ('BA', 'Bosnia and Herzegovina');
insert into country_code values ('BB', 'Barbados');
insert into country_code values ('BD', 'Bangladesh');
insert into country_code values ('BE', 'Belgium');
insert into country_code values ('BF', 'Burkina Faso');
insert into country_code values ('BG', 'Bulgaria');
insert into country_code values ('BH', 'Bahrain');
insert into country_code values ('BI', 'Burundi');
insert into country_code values ('BJ', 'Benin');
insert into country_code values ('BL', 'Saint Barthélemy');
insert into country_code values ('BM', 'Bermuda');
insert into country_code values ('BN', 'Brunei Darussalam');
insert into country_code values ('BO', 'Bolivia (Plurinational State of)');
insert into country_code values ('BQ', 'Bonaire, Sint Eustatius and Saba');
insert into country_code values ('BR', 'Brazil');
insert into country_code values ('BS', 'Bahamas');
insert into country_code values ('BT', 'Bhutan');
insert into country_code values ('BV', 'Bouvet Island');
insert into country_code values ('BW', 'Botswana');
insert into country_code values ('BY', 'Belarus');
insert into country_code values ('BZ', 'Belize');
insert into country_code values ('CA', 'Canada');
insert into country_code values ('CC', 'Cocos (Keeling) Islands');
insert into country_code values ('CD', 'Congo, Democratic Republic of the');
insert into country_code values ('CF', 'Central African Republic');
insert into country_code values ('CG', 'Congo');
insert into country_code values ('CH', 'Switzerland');
insert into country_code values ('CI', 'Côte d''Ivoire');
insert into country_code values ('CK', 'Cook Islands');
insert into country_code values ('CL', 'Chile');
insert into country_code values ('CM', 'Cameroon');
insert into country_code values ('CN', 'China');
insert into country_code values ('CO', 'Colombia');
insert into country_code values ('CR', 'Costa Rica');
insert into country_code values ('CU', 'Cuba');
insert into country_code values ('CV', 'Cabo Verde');
insert into country_code values ('CW', 'Curaçao');
insert into country_code values ('CX', 'Christmas Island');
insert into country_code values ('CY', 'Cyprus');
insert into country_code values ('CZ', 'Czechia');
insert into country_code values ('DE', 'Germany');
insert into country_code values ('DJ', 'Djibouti');
insert into country_code values ('DK', 'Denmark');
insert into country_code values ('DM', 'Dominica');
insert into country_code values ('DO', 'Dominican Republic');
insert into country_code values ('DZ', 'Algeria');
insert into country_code values ('EC', 'Ecuador');
insert into country_code values ('EE', 'Estonia');
insert into country_code values ('EG', 'Egypt');
insert into country_code values ('EH', 'Western Sahara');
insert into country_code values ('ER', 'Eritrea');
insert into country_code values ('ES', 'Spain');
insert into country_code values ('ET', 'Ethiopia');
insert into country_code values ('FI', 'Finland');
insert into country_code values ('FJ', 'Fiji');
insert into country_code values ('FK', 'Falkland Islands (Malvinas)');
insert into country_code values ('FM', 'Micronesia (Federated States of)');
insert into country_code values ('FO', 'Faroe Islands');
insert into country_code values ('FR', 'France');
insert into country_code values ('GA', 'Gabon');
insert into country_code values ('GB', 'United Kingdom of Great Britain and Northern Ireland');
insert into country_code values ('GD', 'Grenada');
insert into country_code values ('GE', 'Georgia');
insert into country_code values ('GF', 'French Guiana');
insert into country_code values ('GG', 'Guernsey');
insert into country_code values ('GH', 'Ghana');
insert into country_code values ('GI', 'Gibraltar');
insert into country_code values ('GL', 'Greenland');
insert into country_code values ('GM', 'Gambia');
insert into country_code values ('GN', 'Guinea');
insert into country_code values ('GP', 'Guadeloupe');
insert into country_code values ('GQ', 'Equatorial Guinea');
insert into country_code values ('GR', 'Greece');
insert into country_code values ('GS', 'South Georgia and the South Sandwich Islands');
insert into country_code values ('GT', 'Guatemala');
insert into country_code values ('GU', 'Guam');
insert into country_code values ('GW', 'Guinea-Bissau');
insert into country_code values ('GY', 'Guyana');
insert into country_code values ('HK', 'Hong Kong');
insert into country_code values ('HM', 'Heard Island and McDonald Islands');
insert into country_code values ('HN', 'Honduras');
insert into country_code values ('HR', 'Croatia');
insert into country_code values ('HT', 'Haiti');
insert into country_code values ('HU', 'Hungary');
insert into country_code values ('ID', 'Indonesia');
insert into country_code values ('IE', 'Ireland');
insert into country_code values ('IL', 'Israel');
insert into country_code values ('IM', 'Isle of Man');
insert into country_code values ('IN', 'India');
insert into country_code values ('IO', 'British Indian Ocean Territory');
insert into country_code values ('IQ', 'Iraq');
insert into country_code values ('IR', 'Iran (Islamic Republic of)');
insert into country_code values ('IS', 'Iceland');
insert into country_code values ('IT', 'Italy');
insert into country_code values ('JE', 'Jersey');
insert into country_code values ('JM', 'Jamaica');
insert into country_code values ('JO', 'Jordan');
insert into country_code values ('JP', 'Japan');
insert into country_code values ('KE', 'Kenya');
insert into country_code values ('KG', 'Kyrgyzstan');
insert into country_code values ('KH', 'Cambodia');
insert into country_code values ('KI', 'Kiribati');
insert into country_code values ('KM', 'Comoros');
insert into country_code values ('KN', 'Saint Kitts and Nevis');
insert into country_code values ('KP', 'Korea (Democratic People''s Republic of)');
insert into country_code values ('KR', 'Korea, Republic of');
insert into country_code values ('KW', 'Kuwait');
insert into country_code values ('KY', 'Cayman Islands');
insert into country_code values ('KZ', 'Kazakhstan');
insert into country_code values ('LA', 'Lao People''s Democratic Republic');
insert into country_code values ('LB', 'Lebanon');
insert into country_code values ('LC', 'Saint Lucia');
insert into country_code values ('LI', 'Liechtenstein');
insert into country_code values ('LK', 'Sri Lanka');
insert into country_code values ('LR', 'Liberia');
insert into country_code values ('LS', 'Lesotho');
insert into country_code values ('LT', 'Lithuania');
insert into country_code values ('LU', 'Luxembourg');
insert into country_code values ('LV', 'Latvia');
insert into country_code values ('LY', 'Libya');
insert into country_code values ('MA', 'Morocco');
insert into country_code values ('MC', 'Monaco');
insert into country_code values ('MD', 'Moldova, Republic of');
insert into country_code values ('ME', 'Montenegro');
insert into country_code values ('MF', 'Saint Martin (French part)');
insert into country_code values ('MG', 'Madagascar');
insert into country_code values ('MH', 'Marshall Islands');
insert into country_code values ('MK', 'North Macedonia');
insert into country_code values ('ML', 'Mali');
insert into country_code values ('MM', 'Myanmar');
insert into country_code values ('MN', 'Mongolia');
insert into country_code values ('MO', 'Macao');
insert into country_code values ('MP', 'Northern Mariana Islands');
insert into country_code values ('MQ', 'Martinique');
insert into country_code values ('MR', 'Mauritania');
insert into country_code values ('MS', 'Montserrat');
insert into country_code values ('MT', 'Malta');
insert into country_code values ('MU', 'Mauritius');
insert into country_code values ('MV', 'Maldives');
insert into country_code values ('MW', 'Malawi');
insert into country_code values ('MX', 'Mexico');
insert into country_code values ('MY', 'Malaysia');
insert into country_code values ('MZ', 'Mozambique');
insert into country_code values ('NA', 'Namibia');
insert into country_code values ('NC', 'New Caledonia');
insert into country_code values ('NE', 'Niger');
insert into country_code values ('NF', 'Norfolk Island');
insert into country_code values ('NG', 'Nigeria');
insert into country_code values ('NI', 'Nicaragua');
insert into country_code values ('NL', 'Netherlands');
insert into country_code values ('NO', 'Norway');
insert into country_code values ('NP', 'Nepal');
insert into country_code values ('NR', 'Nauru');
insert into country_code values ('NU', 'Niue');
insert into country_code values ('NZ', 'New Zealand');
insert into country_code values ('OM', 'Oman');
insert into country_code values ('PA', 'Panama');
insert into country_code values ('PE', 'Peru');
insert into country_code values ('PF', 'French Polynesia');
insert into country_code values ('PG', 'Papua New Guinea');
insert into country_code values ('PH', 'Philippines');
insert into country_code values ('PK', 'Pakistan');
insert into country_code values ('PL', 'Poland');
insert into country_code values ('PM', 'Saint Pierre and Miquelon');
insert into country_code values ('PN', 'Pitcairn');
insert into country_code values ('PR', 'Puerto Rico');
insert into country_code values ('PS', 'Palestine, State of');
insert into country_code values ('PT', 'Portugal');
insert into country_code values ('PW', 'Palau');
insert into country_code values ('PY', 'Paraguay');
insert into country_code values ('QA', 'Qatar');
insert into country_code values ('RE', 'Réunion');
insert into country_code values ('RO', 'Romania');
insert into country_code values ('RS', 'Serbia');
insert into country_code values ('RU', 'Russian Federation');
insert into country_code values ('RW', 'Rwanda');
insert into country_code values ('SA', 'Saudi Arabia');
insert into country_code values ('SB', 'Solomon Islands');
insert into country_code values ('SC', 'Seychelles');
insert into country_code values ('SD', 'Sudan');
insert into country_code values ('SE', 'Sweden');
insert into country_code values ('SG', 'Singapore');
insert into country_code values ('SH', 'Saint Helena, Ascension and Tristan da Cunha');
insert into country_code values ('SI', 'Slovenia');
insert into country_code values ('SJ', 'Svalbard and Jan Mayen');
insert into country_code values ('SK', 'Slovakia');
insert into country_code values ('SL', 'Sierra Leone');
insert into country_code values ('SM', 'San Marino');
insert into country_code values ('SN', 'Senegal');
insert into country_code values ('SO', 'Somalia');
insert into country_code values ('SR', 'Suriname');
insert into country_code values ('SS', 'South Sudan');
insert into country_code values ('ST', 'Sao Tome and Principe');
insert into country_code values ('SV', 'El Salvador');
insert into country_code values ('SX', 'Sint Maarten (Dutch part)');
insert into country_code values ('SY', 'Syrian Arab Republic');
insert into country_code values ('SZ', 'Eswatini');
insert into country_code values ('TC', 'Turks and Caicos Islands');
insert into country_code values ('TD', 'Chad');
insert into country_code values ('TF', 'French Southern Territories');
insert into country_code values ('TG', 'Togo');
insert into country_code values ('TH', 'Thailand');
insert into country_code values ('TJ', 'Tajikistan');
insert into country_code values ('TK', 'Tokelau');
insert into country_code values ('TL', 'Timor-Leste');
insert into country_code values ('TM', 'Turkmenistan');
insert into country_code values ('TN', 'Tunisia');
insert into country_code values ('TO', 'Tonga');
insert into country_code values ('TR', 'Turkey');
insert into country_code values ('TT', 'Trinidad and Tobago');
insert into country_code values ('TV', 'Tuvalu');
insert into country_code values ('TW', 'Taiwan, Province of China');
insert into country_code values ('TZ', 'Tanzania, United Republic of');
insert into country_code values ('UA', 'Ukraine');
insert into country_code values ('UG', 'Uganda');
insert into country_code values ('UM', 'United States Minor Outlying Islands');
insert into country_code values ('US', 'United States of America');
insert into country_code values ('UY', 'Uruguay');
insert into country_code values ('UZ', 'Uzbekistan');
insert into country_code values ('V', '');
insert into country_code values ('W', '');
insert into country_code values ('X', '');
insert into country_code values ('Y', '');
insert into country_code values ('Z', '');
commit;

drop table earth_marker_tb;
create table earth_marker_tb (
    alpha_two_code varchar2(2) references country_code,
    landmark varchar2(64),
    latitude number,
    longitude number,
    img_url varchar2(2048)
);

insert into earth_marker_tb values ('AU', 'Sydney Opera House', -33.85678581090873, 151.21529563018993, 'https://www.listchallenges.com/f/items/baccf057-63ee-4aa5-aab6-f0f1212d8fb7.jpg');
insert into earth_marker_tb values ('AU', 'Uluru', -25.34442935146111, 131.03688205246655, 'https://www.listchallenges.com/f/items/7fb2cd5d-8abc-40a8-a25d-5aa7c8ebd216.jpg');
insert into earth_marker_tb values ('BR', 'Christ the Redeemer', -22.95191766707672, -43.21048718358794, 'https://www.listchallenges.com/f/items/00472c34-0bbb-495c-8d3d-15b4e77918d1.jpg');
insert into earth_marker_tb values ('CL', 'Moai', -27.143964210405834, -109.33049923928347, 'https://www.listchallenges.com/f/items/6113cc48-e777-4474-bad1-481f7abd07d3.jpg');
insert into earth_marker_tb values ('CN', 'Great Wall of China', 40.43190625811218, 116.57037462757219, 'https://www.listchallenges.com/f/items/a0015a10-617f-4077-a734-1d030ed48058.jpg');
insert into earth_marker_tb values ('DE', 'Berlin Wall', 52.507180294878474, 13.38350549528898, 'https://www.listchallenges.com/f/items/ecf6bcac-2010-4b2a-bfba-a138602c9610.jpg');
insert into earth_marker_tb values ('DK', 'Nyhavn', 55.67977493741472, 12.591304414302332, 'https://www.listchallenges.com/f/items-dl/5f61f3d7-e72f-4a00-b729-e8b8b6167aef.jpg');
insert into earth_marker_tb values ('EG', 'Great Pyramid of Giza', 29.97923299710245, 31.13420122099721, 'https://www.listchallenges.com/f/items/66b160d7-d2f9-4dca-887b-ae38651e69c7.jpg');
insert into earth_marker_tb values ('FR', 'Eiffel Tower', 48.85836913732332, 2.2944810216658094, 'https://www.listchallenges.com/f/items/4e76ea71-f275-44df-a98f-0f75f9771a65.jpg');
insert into earth_marker_tb values ('GB', 'Big Ben', 51.50072808026876, -0.1246256436939679, 'https://www.listchallenges.com/f/items/2c6fce4f-e410-4d50-80b6-870bc945b17b.jpg');
insert into earth_marker_tb values ('GB', 'Stonehenge', 51.17888055584205, -1.8262150592416728, 'https://www.listchallenges.com/f/items/a5f9eb7d-71f2-4710-a4c6-7c04a634c319.jpg');
insert into earth_marker_tb values ('IE', 'Newgrange', 53.69471085263502, -6.47549176030871, 'https://www.listchallenges.com/f/items/cea40c98-ae81-4980-8d43-07ba977917a3.jpg');
insert into earth_marker_tb values ('IL', 'Western Wall', 31.776717233209467, 35.2345079964759, 'https://www.listchallenges.com/f/items/6b3f2257-1ed4-4273-ad2f-48bc567820ed.jpg');
insert into earth_marker_tb values ('IN', 'Taj Mahal', 27.175143641271443, 78.0421416446706, 'https://www.listchallenges.com/f/items/4dd9d779-3bc9-49d8-89d5-a34b133c6ab3.jpg');
insert into earth_marker_tb values ('IT', 'Colosseum', 41.89020864142666, 12.492230497868867, 'https://www.listchallenges.com/f/items/e71fd9ad-6027-44f2-93df-b0a284507c74.jpg');
insert into earth_marker_tb values ('IT', 'Leaning Tower of Pisa', 43.722950638562374, 10.396596501335175, 'https://www.listchallenges.com/f/items/bb1fa37e-fd85-43ef-87a6-02387af5dc25.jpg');
insert into earth_marker_tb values ('JP', 'Tokyo Tower', 35.65857925940548, 139.7454328672275, 'https://www.listchallenges.com/f/items/314a88a3-11a8-43cf-9369-4ce047cd0dfc.jpg');
insert into earth_marker_tb values ('KR', 'Gyeongbokgung', 37.57961546157773, 126.97704023412163, 'https://lh5.googleusercontent.com/proxy/XmnHVngvJ-_FVag6Ma79DoDsi0qverft5987BW75y6GNmBPr_G_mJJptp_TfLztBfDRbZxUOjb4xwd2u-b43X4FtGGhqOrSMN9yRO6ik_GSMCBbgb2uiFuMhSCWuL9iSttVS2afN9fYBZH6bZXZkUDknj0GnMo8=w408-h270-k-no');
insert into earth_marker_tb values ('RU', 'St. Basil''s Cathedral', 55.7525218404382, 37.62308709017052, 'https://www.listchallenges.com/f/items/8e410b50-6290-4c99-b92a-4bac3cb8b719.jpg');
insert into earth_marker_tb values ('TZ', 'Mount Kilimanjaro', -3.067426845692697, 37.35562636976589, 'https://www.listchallenges.com/f/items/0b047c9f-99e5-4f38-83f8-547f2dbe085f.jpg');
insert into earth_marker_tb values ('US', 'Golden Gate Bridge', 37.8199116294378, -122.47825510205308, 'https://www.listchallenges.com/f/items/6b26ad11-44d1-497c-897b-65ae86f67273.jpg');
insert into earth_marker_tb values ('US', 'Hollywood', 26.011513680538773, -80.14304728416546, 'https://www.listchallenges.com/f/items/db282a05-f160-40b3-8129-035bcd322ccb.jpg');
insert into earth_marker_tb values ('US', 'Statue of Liberty', 40.68924788775158, -74.04450128301255, 'https://www.listchallenges.com/f/items/a45acde9-68c5-4871-b49c-0a630890076b.jpg');
commit;
