DROP TABLE country_code_tb;
CREATE TABLE country_code_tb(
    alpha_two_code  VARCHAR2(2)  PRIMARY KEY,
    country_name    VARCHAR2(56)
);

INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('AD', 'Andorra');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('AE', 'United Arab Emirates');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('AF', 'Afghanistan');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('AG', 'Antigua and Barbuda');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('AI', 'Anguilla');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('AL', 'Albania');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('AM', 'Armenia');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('AO', 'Angola');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('AQ', 'Antarctica');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('AR', 'Argentina');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('AS', 'American Samoa');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('AT', 'Austria');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('AU', 'Australia');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('AW', 'Aruba');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('AX', 'Åland Islands');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('AZ', 'Azerbaijan');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('BA', 'Bosnia and Herzegovina');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('BB', 'Barbados');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('BD', 'Bangladesh');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('BE', 'Belgium');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('BF', 'Burkina Faso');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('BG', 'Bulgaria');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('BH', 'Bahrain');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('BI', 'Burundi');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('BJ', 'Benin');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('BL', 'Saint Barthélemy');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('BM', 'Bermuda');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('BN', 'Brunei Darussalam');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('BO', 'Bolivia (Plurinational State of)');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('BQ', 'Bonaire, Sint Eustatius and Saba');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('BR', 'Brazil');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('BS', 'Bahamas');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('BT', 'Bhutan');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('BV', 'Bouvet Island');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('BW', 'Botswana');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('BY', 'Belarus');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('BZ', 'Belize');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('CA', 'Canada');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('CC', 'Cocos (Keeling) Islands');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('CD', 'Congo, Democratic Republic of the');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('CF', 'Central African Republic');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('CG', 'Congo');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('CH', 'Switzerland');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('CI', 'Côte d''Ivoire');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('CK', 'Cook Islands');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('CL', 'Chile');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('CM', 'Cameroon');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('CN', 'China');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('CO', 'Colombia');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('CR', 'Costa Rica');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('CU', 'Cuba');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('CV', 'Cabo Verde');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('CW', 'Curaçao');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('CX', 'Christmas Island');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('CY', 'Cyprus');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('CZ', 'Czechia');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('DE', 'Germany');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('DJ', 'Djibouti');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('DK', 'Denmark');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('DM', 'Dominica');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('DO', 'Dominican Republic');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('DZ', 'Algeria');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('EC', 'Ecuador');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('EE', 'Estonia');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('EG', 'Egypt');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('EH', 'Western Sahara');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('ER', 'Eritrea');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('ES', 'Spain');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('ET', 'Ethiopia');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('FI', 'Finland');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('FJ', 'Fiji');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('FK', 'Falkland Islands (Malvinas)');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('FM', 'Micronesia (Federated States of)');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('FO', 'Faroe Islands');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('FR', 'France');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('GA', 'Gabon');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('GB', 'United Kingdom of Great Britain and Northern Ireland');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('GD', 'Grenada');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('GE', 'Georgia');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('GF', 'French Guiana');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('GG', 'Guernsey');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('GH', 'Ghana');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('GI', 'Gibraltar');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('GL', 'Greenland');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('GM', 'Gambia');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('GN', 'Guinea');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('GP', 'Guadeloupe');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('GQ', 'Equatorial Guinea');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('GR', 'Greece');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('GS', 'South Georgia and the South Sandwich Islands');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('GT', 'Guatemala');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('GU', 'Guam');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('GW', 'Guinea-Bissau');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('GY', 'Guyana');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('HK', 'Hong Kong');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('HM', 'Heard Island and McDonald Islands');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('HN', 'Honduras');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('HR', 'Croatia');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('HT', 'Haiti');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('HU', 'Hungary');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('ID', 'Indonesia');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('IE', 'Ireland');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('IL', 'Israel');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('IM', 'Isle of Man');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('IN', 'India');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('IO', 'British Indian Ocean Territory');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('IQ', 'Iraq');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('IR', 'Iran (Islamic Republic of)');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('IS', 'Iceland');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('IT', 'Italy');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('JE', 'Jersey');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('JM', 'Jamaica');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('JO', 'Jordan');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('JP', 'Japan');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('KE', 'Kenya');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('KG', 'Kyrgyzstan');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('KH', 'Cambodia');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('KI', 'Kiribati');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('KM', 'Comoros');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('KN', 'Saint Kitts and Nevis');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('KP', 'Korea (Democratic People''s Republic of)');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('KR', 'Korea, Republic of');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('KW', 'Kuwait');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('KY', 'Cayman Islands');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('KZ', 'Kazakhstan');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('LA', 'Lao People''s Democratic Republic');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('LB', 'Lebanon');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('LC', 'Saint Lucia');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('LI', 'Liechtenstein');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('LK', 'Sri Lanka');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('LR', 'Liberia');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('LS', 'Lesotho');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('LT', 'Lithuania');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('LU', 'Luxembourg');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('LV', 'Latvia');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('LY', 'Libya');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('MA', 'Morocco');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('MC', 'Monaco');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('MD', 'Moldova, Republic of');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('ME', 'Montenegro');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('MF', 'Saint Martin (French part)');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('MG', 'Madagascar');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('MH', 'Marshall Islands');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('MK', 'North Macedonia');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('ML', 'Mali');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('MM', 'Myanmar');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('MN', 'Mongolia');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('MO', 'Macao');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('MP', 'Northern Mariana Islands');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('MQ', 'Martinique');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('MR', 'Mauritania');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('MS', 'Montserrat');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('MT', 'Malta');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('MU', 'Mauritius');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('MV', 'Maldives');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('MW', 'Malawi');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('MX', 'Mexico');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('MY', 'Malaysia');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('MZ', 'Mozambique');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('NA', 'Namibia');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('NC', 'New Caledonia');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('NE', 'Niger');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('NF', 'Norfolk Island');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('NG', 'Nigeria');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('NI', 'Nicaragua');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('NL', 'Netherlands');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('NO', 'Norway');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('NP', 'Nepal');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('NR', 'Nauru');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('NU', 'Niue');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('NZ', 'New Zealand');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('OM', 'Oman');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('PA', 'Panama');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('PE', 'Peru');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('PF', 'French Polynesia');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('PG', 'Papua New Guinea');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('PH', 'Philippines');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('PK', 'Pakistan');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('PL', 'Poland');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('PM', 'Saint Pierre and Miquelon');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('PN', 'Pitcairn');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('PR', 'Puerto Rico');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('PS', 'Palestine, State of');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('PT', 'Portugal');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('PW', 'Palau');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('PY', 'Paraguay');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('QA', 'Qatar');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('RE', 'Réunion');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('RO', 'Romania');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('RS', 'Serbia');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('RU', 'Russian Federation');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('RW', 'Rwanda');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('SA', 'Saudi Arabia');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('SB', 'Solomon Islands');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('SC', 'Seychelles');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('SD', 'Sudan');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('SE', 'Sweden');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('SG', 'Singapore');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('SH', 'Saint Helena, Ascension and Tristan da Cunha');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('SI', 'Slovenia');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('SJ', 'Svalbard and Jan Mayen');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('SK', 'Slovakia');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('SL', 'Sierra Leone');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('SM', 'San Marino');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('SN', 'Senegal');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('SO', 'Somalia');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('SR', 'Suriname');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('SS', 'South Sudan');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('ST', 'Sao Tome and Principe');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('SV', 'El Salvador');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('SX', 'Sint Maarten (Dutch part)');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('SY', 'Syrian Arab Republic');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('SZ', 'Eswatini');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('TC', 'Turks and Caicos Islands');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('TD', 'Chad');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('TF', 'French Southern Territories');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('TG', 'Togo');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('TH', 'Thailand');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('TJ', 'Tajikistan');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('TK', 'Tokelau');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('TL', 'Timor-Leste');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('TM', 'Turkmenistan');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('TN', 'Tunisia');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('TO', 'Tonga');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('TR', 'Turkey');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('TT', 'Trinidad and Tobago');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('TV', 'Tuvalu');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('TW', 'Taiwan, Province of China');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('TZ', 'Tanzania, United Republic of');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('UA', 'Ukraine');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('UG', 'Uganda');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('UM', 'United States Minor Outlying Islands');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('US', 'United States of America');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('UY', 'Uruguay');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('UZ', 'Uzbekistan');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('VA', 'Holy See');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('VC', 'Saint Vincent and the Grenadines');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('VE', 'Venezuela (Bolivarian Republic of)');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('VG', 'Virgin Islands (British)');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('VI', 'Virgin Islands (U.S.)');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('VN', 'Viet Nam');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('VU', 'Vanuatu');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('WF', 'Wallis and Futuna');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('WS', 'Samoa');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('YE', 'Yemen');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('YT', 'Mayotte');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('ZA', 'South Africa');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('ZM', 'Zambia');
INSERT INTO country_code_tb (alpha_two_code, country_name) VALUES ('ZW', 'Zimbabwe');
COMMIT;

DROP TABLE landmark_tb;
CREATE TABLE landmark_tb (
    alpha_two_code  VARCHAR2(2) REFERENCES country_code_tb ON DELETE CASCADE,
    landmark        VARCHAR2(64),
    latitude        NUMBER,
    longitude       NUMBER,
    img_url         VARCHAR2(2048)
);

INSERT INTO landmark_tb VALUES ('AU', 'Sydney Opera House', -33.85678581090873, 151.21529563018993, 'https://www.listchallenges.com/f/items/baccf057-63ee-4aa5-aab6-f0f1212d8fb7.jpg');
INSERT INTO landmark_tb VALUES ('AU', 'Uluru', -25.34442935146111, 131.03688205246655, 'https://www.listchallenges.com/f/items/7fb2cd5d-8abc-40a8-a25d-5aa7c8ebd216.jpg');
INSERT INTO landmark_tb VALUES ('BR', 'Christ the Redeemer', -22.95191766707672, -43.21048718358794, 'https://www.listchallenges.com/f/items/00472c34-0bbb-495c-8d3d-15b4e77918d1.jpg');
INSERT INTO landmark_tb VALUES ('CL', 'Moai', -27.143964210405834, -109.33049923928347, 'https://www.listchallenges.com/f/items/6113cc48-e777-4474-bad1-481f7abd07d3.jpg');
INSERT INTO landmark_tb VALUES ('CN', 'Great Wall of China', 40.43190625811218, 116.57037462757219, 'https://www.listchallenges.com/f/items/a0015a10-617f-4077-a734-1d030ed48058.jpg');
INSERT INTO landmark_tb VALUES ('DE', 'Berlin Wall', 52.507180294878474, 13.38350549528898, 'https://www.listchallenges.com/f/items/ecf6bcac-2010-4b2a-bfba-a138602c9610.jpg');
INSERT INTO landmark_tb VALUES ('DK', 'Nyhavn', 55.67977493741472, 12.591304414302332, 'https://www.listchallenges.com/f/items-dl/5f61f3d7-e72f-4a00-b729-e8b8b6167aef.jpg');
INSERT INTO landmark_tb VALUES ('EG', 'Great Pyramid of Giza', 29.97923299710245, 31.13420122099721, 'https://www.listchallenges.com/f/items/66b160d7-d2f9-4dca-887b-ae38651e69c7.jpg');
INSERT INTO landmark_tb VALUES ('FR', 'Eiffel Tower', 48.85836913732332, 2.2944810216658094, 'https://www.listchallenges.com/f/items/4e76ea71-f275-44df-a98f-0f75f9771a65.jpg');
INSERT INTO landmark_tb VALUES ('GB', 'Big Ben', 51.50072808026876, -0.1246256436939679, 'https://www.listchallenges.com/f/items/2c6fce4f-e410-4d50-80b6-870bc945b17b.jpg');
INSERT INTO landmark_tb VALUES ('GB', 'Stonehenge', 51.17888055584205, -1.8262150592416728, 'https://www.listchallenges.com/f/items/a5f9eb7d-71f2-4710-a4c6-7c04a634c319.jpg');
INSERT INTO landmark_tb VALUES ('IE', 'Newgrange', 53.69471085263502, -6.47549176030871, 'https://www.listchallenges.com/f/items/cea40c98-ae81-4980-8d43-07ba977917a3.jpg');
INSERT INTO landmark_tb VALUES ('IL', 'Western Wall', 31.776717233209467, 35.2345079964759, 'https://www.listchallenges.com/f/items/6b3f2257-1ed4-4273-ad2f-48bc567820ed.jpg');
INSERT INTO landmark_tb VALUES ('IN', 'Taj Mahal', 27.175143641271443, 78.0421416446706, 'https://www.listchallenges.com/f/items/4dd9d779-3bc9-49d8-89d5-a34b133c6ab3.jpg');
INSERT INTO landmark_tb VALUES ('IT', 'Colosseum', 41.89020864142666, 12.492230497868867, 'https://www.listchallenges.com/f/items/e71fd9ad-6027-44f2-93df-b0a284507c74.jpg');
INSERT INTO landmark_tb VALUES ('IT', 'Leaning Tower of Pisa', 43.722950638562374, 10.396596501335175, 'https://www.listchallenges.com/f/items/bb1fa37e-fd85-43ef-87a6-02387af5dc25.jpg');
INSERT INTO landmark_tb VALUES ('JP', 'Tokyo Tower', 35.65857925940548, 139.7454328672275, 'https://www.listchallenges.com/f/items/314a88a3-11a8-43cf-9369-4ce047cd0dfc.jpg');
INSERT INTO landmark_tb VALUES ('KR', 'Gyeongbokgung', 37.57961546157773, 126.97704023412163, 'https://lh5.googleusercontent.com/proxy/XmnHVngvJ-_FVag6Ma79DoDsi0qverft5987BW75y6GNmBPr_G_mJJptp_TfLztBfDRbZxUOjb4xwd2u-b43X4FtGGhqOrSMN9yRO6ik_GSMCBbgb2uiFuMhSCWuL9iSttVS2afN9fYBZH6bZXZkUDknj0GnMo8=w408-h270-k-no');
INSERT INTO landmark_tb VALUES ('RU', 'St. Basil''s Cathedral', 55.7525218404382, 37.62308709017052, 'https://www.listchallenges.com/f/items/8e410b50-6290-4c99-b92a-4bac3cb8b719.jpg');
INSERT INTO landmark_tb VALUES ('TZ', 'Mount Kilimanjaro', -3.067426845692697, 37.35562636976589, 'https://www.listchallenges.com/f/items/0b047c9f-99e5-4f38-83f8-547f2dbe085f.jpg');
INSERT INTO landmark_tb VALUES ('US', 'Golden Gate Bridge', 37.8199116294378, -122.47825510205308, 'https://www.listchallenges.com/f/items/6b26ad11-44d1-497c-897b-65ae86f67273.jpg');
INSERT INTO landmark_tb VALUES ('US', 'Hollywood', 26.011513680538773, -80.14304728416546, 'https://www.listchallenges.com/f/items/db282a05-f160-40b3-8129-035bcd322ccb.jpg');
INSERT INTO landmark_tb VALUES ('US', 'Statue of Liberty', 40.68924788775158, -74.04450128301255, 'https://www.listchallenges.com/f/items/a45acde9-68c5-4871-b49c-0a630890076b.jpg');
COMMIT;
